project:
  type: website

website:
  title: "My Software Dev"
  sidebar:
    style: docked
    search: true
    contents:
      - href: docs/index.qmd
        text: Home
        contents:
          - href: docs/about.qmd
            text: About this site
      - section: Data Exploring
        text: Data Exploring
        contents:
          - href: docs/notebooks/geopandas.qmd
            text: Explore GeoJSON
          - href: docs/notebooks/demo.qmd
            text: Demo Notebook
          - href: docs/notebooks/opensky.qmd
            text: OpenSky flights geo
      - section: Data Resources
        text: Data Resources
        contents:
          - href: docs/resources/adsb.qmd
            text: ADS-B
          - href: docs/resources/ais.qmd
            text: AIS
          - href: docs/resources/aksjeeiere.qmd
            text: Aksjeeiere
          - href: docs/resources/arduino.qmd
            text: Arduino
          - href: docs/resources/carregno.qmd
            text: Carreg.no
          - href: docs/resources/eiendomspriser.qmd
            text: Eiendomspriser
          - href: docs/resources/frost.qmd
            text: Frost
          - href: docs/resources/gtfs.qmd
            text: GTFS
          - href: docs/resources/nordpool.qmd
            text: Nordpool
          - href: docs/resources/nrk.qmd
            text: NRK
          - href: docs/resources/ruter.qmd
            text: Ruter.no
          - href: docs/resources/statensvegvesen.qmd
            text: Statens Vegvesen
          - href: docs/resources/trafiklabs_se.qmd
            text: Trafiklab.se
          - href: docs/resources/weather.qmd
            text: Weather
      - section: Data Resources
        text: Data Resources
        contents:
          - href: docs/3dprint.qmd
            text: 3D Print
          - href: docs/3dprint/samples.qmd
            text: Skeleton sampes
      - href: docs/projectideas.qmd
        text: Project Ideas
      - href: docs/spar10.qmd
        text: Sparetider

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



