project:
  type: website

website:
  title: "My Software Dev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 3dprint.qmd
      - projectideas.qmd
      - spar10.qmd
      - resources/adsb.qmd
      - resources/ais.qmd
      - resources/aksjeeiere.qmd
      - resources/arduino.qmd
      - resources/carregno.qmd
      - resources/eiendomspriser.qmd
      - resources/frost.qmd
      - resources/gtfs.qmd
      - resources/nordpool.qmd
      - resources/nrk.qmd
      - resources/ruter.qmd
      - resources/statensvegvesen.qmd
      - resources/trafiklabs_se.qmd
      - resources/weather.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



