project:
  type: website

website:
  title: "My Software Dev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 3dprint.qmd
      - about.qmd
      - resources/adsb.qmd
      - resources/ais.qmd
      - resources/akseiere.qmd
      - resources/arduino.qmd
      - resources/gtfs.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



