project:
  type: website

website:
  title: "My Software Dev"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
        contents:
          - href: about.qmd
            text: About this site
      - section: Data Resources
        text: Data Resources
        contents:
          - href: resources/adsb.qmd
            text: ADS-B
          - href: resources/ais.qmd
            text: AIS
          - href: resources/aksjeeiere.qmd
            text: Aksjeeiere
          - href: resources/arduino.qmd
            text: Arduino
          - href: resources/carregno.qmd
            text: Carreg.no
          - href: resources/eiendomspriser.qmd
            text: Eiendomspriser
          - href: resources/frost.qmd
            text: Frost
          - href: resources/gtfs.qmd
            text: GTFS
          - href: resources/nordpool.qmd
            text: Nordpool
          - href: resources/nrk.qmd
            text: NRK
          - href: resources/ruter.qmd
            text: Ruter.no
          - href: resources/statensvegvesen.qmd
            text: Statens Vegvesen
          - href: resources/trafiklabs_se.qmd
            text: Trafiklab.se
          - href: resources/weather.qmd
            text: Weather
      - href: 3dprint.qmd
        text: 3D Print
      - href: projectideas.qmd
        text: Project Ideas
      - href: spar10.qmd
        text: Sparetider

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



